name: Setup ARM remote builder

runs:
  using: composite
  steps:
    - shell: sudo bash -e {0}
      run: |
        echo >> /etc/ssh/sshd_config \
          PermitEmptyPasswords yes

        echo >> /etc/ssh/ssh_config '
        Host *
          # BatchMode yes
          StrictHostKeyChecking no

        Host proxy-jump
          HostName ssh-j.com
          User ${{ github.repository }}/${{ github.run_id }}
          RemoteForward arm-builder:22 localhost:22
          ExitOnForwardFailure yes

        Host arm-builder
          ProxyJump proxy-jump
          User runner
        '

        cat /etc/pam.d/sshd /etc/pam.d/common-*
        systemctl restart ssh

    - shell: bash
      run: |
        echo "NIX_CONFIG<<'
          builders = ssh-ng://arm-builder aarch64-linux - $(nproc)
          builders-use-substitutes = true
        '" >> $GITHUB_ENV
