name: Setup ARM remote builder

runs:
  using: composite
  steps:
    - shell: sudo bash {0}
      run: |
        usermod runner -p '' -s $SHELL

        echo > /etc/ssh/sshd_config \
          PermitEmptyPasswords yes

        echo > /etc/ssh/ssh_config '
          BatchMode yes
          StrictHostKeyChecking no

        Host proxy-jump
          HostName ssh-j.com
          User ${{ github.repository }}/${{ github.run_id }}
          ControlPath ${XDG_RUNTIME_DIR}/ssh-%C.sock
          RemoteForward arm-builder:22 localhost:22
          ExitOnForwardFailure yes

        Host arm-builder
          ProxyJump proxy-jump
          User runner
        '

    - if: ${{ startsWith(runner.arch, 'arm') }}
      shell: bash
      run: |
        ssh proxy-jump -MfN

        while ssh proxy-jump -O check 2> /dev/null; do
          drvs=$(nix ps --json | jq -r '.[].derivation' | tee >(
            grep -v "${drvs:-:}" | sed 's.^.building /nix/store/.' >&2
          ))
        done

    - if: ${{ !startsWith(runner.arch, 'arm') }}
      uses: gacts/run-and-post-run@main
      with:
        run: echo >> $GITHUB_ENV NIX_CONFIG=builders =
          ssh-ng://arm-builder aarch64-linux - $(nproc)
        post: ssh arm-builder ssh proxy-jump -O exit
