name: Install Determinate Nix

runs:
  using: "composite"
  steps:
    - shell: bash
      env:
        GH_TOKEN: ${{ github.token }}
        NIX_REPO: DeterminateSystems/nix-src
      run: |
        gh --repo $NIX_REPO run download $(
          gh --repo $NIX_REPO run list --event release \
            --json databaseId --jq '.[0].databaseId'
        ) --name $(uname -m)-linux --dir /tmp

        tar -xf /tmp/nix-*.tar.xz -C /tmp
        ln -s /tmp/nix-*/installer /tmp/nix-installer

    - uses: cachix/install-nix-action@master
      with:
        install_url: file:///tmp/nix-installer
