name: Install Determinate Nix
inputs:
  cachix-auth-token:

runs:
  using: composite
  steps:
    - working-directory: /tmp
      env:
        GH_TOKEN: ${{ github.token }}
        NIX_REPO: DeterminateSystems/nix-src

      shell: bash
      run: |
        gh --repo $NIX_REPO run download $(
          gh --repo $NIX_REPO run list --event release \
            --json databaseId --jq '.[0].databaseId'
        ) --name $(uname -m)-linux

        tar -xf nix-*.tar.xz
        echo /tmp/nix-*/install '"$@"' > nix-install

    - uses: wimpysworld/nothing-but-nix@main
    - uses: cachix/install-nix-action@master
      with:
        install_url: file:///tmp/nix-install
        extra_nix_config: |
          lazy-locks = true
          lazy-trees = true
          eval-cores = 0
          builders-use-substitutes = true

    - if: inputs.cachix-auth-token
      uses: cachix/cachix-action@master
      with:
        name: ${{ github.repository_owner }}
        authToken: ${{ inputs.cachix-auth-token }}
