name: Install Determinate Nix

runs:
  using: "composite"
  steps:
    - shell: bash
      env:
        GH_TOKEN: ${{ github.token }}
        NIX_REPO: DeterminateSystems/nix-src
      run: |
        cd /tmp

        gh --repo $NIX_REPO run download $(
          gh --repo $NIX_REPO run list --event release \
            --json databaseId --jq '.[0].databaseId'
        ) --name $(uname -m)-linux

        tar -xf nix-*.tar.xz
        echo nix-*/install > nix-install

    - uses: cachix/install-nix-action@master
      with:
        install_url: file:///tmp/nix-install
