name: Setup ARM remote builder
on:
  workflow_call:
  workflow_dispatch:

env:
  JUMP_PROXY: ${{ github.repository }}@ssh-j.com
  ARM_BUILDER: arm-builder-${{ github.run_id }}

jobs:
  setup-arm-builder:
    runs-on: ubuntu-24.04-arm
    steps:
      - uses: wimpysworld/nothing-but-nix@main
      - uses: DeterminateSystems/nix-installer-action@main
        with:
          extra-conf: |
            lazy-locks = true
            lazy-trees = true
            eval-cores = 0

      - uses: actions/checkout@main
      - run: nix run home-manager -- switch
          --flake .#$(nix config show system)
          --accept-flake-config
          --trace-verbose --show-trace
          --print-build-logs --keep-going

      - run: |
          mkdir -p ~/.ssh
          ssh-keygen -t rsa -N '' -f ~/.ssh/id_rsa
          cp ~/.ssh/id_rsa.pub ~/.ssh/authorized_keys

          printf > ~/.ssh/config "
            Host * \n StrictHostKeyChecking no
            Host $ARM_BUILDER \n ProxyJump $JUMP_PROXY
          "

          sudo cp -R ~/.ssh /root
          sudo chown -R root:root /root/.ssh

      - uses: actions/upload-artifact@main
        with:
          name: .ssh
          path: ~/.ssh
          include-hidden-files: true
          if-no-files-found: error

      - run: ssh $JUMP_PROXY -NR $ARM_BUILDER:22:localhost:22
