name: Setup ARM remote builder
on:
  workflow_call:
  workflow_dispatch:

env:
  JUMP_PROXY: ${{ github.repository }}@ssh-j.com
  ARM_BUILDER: arm-builder-${{ github.run_id }}

jobs:
  setup-arm-builder:
    permissions: {}

    runs-on: ubuntu-24.04-arm
    steps:
      - uses: wimpysworld/nothing-but-nix@main
      - uses: DeterminateSystems/nix-installer-action@main

      - run: |
          mkdir -p ~/.ssh ~/.config/nix
          ssh-keygen -t rsa -N '' -f ~/.ssh/id_rsa
          cp ~/.ssh/id_rsa.pub ~/.ssh/authorized_keys

          printf > ~/.ssh/config "
            Host * \n StrictHostKeyChecking no
            Host $ARM_BUILDER \n ProxyJump $JUMP_PROXY
          "

      - run: |
          printf > ~/.config/nix/nix.conf "
            builders = ssh-ng://$ARM_BUILDER %s - %s - %s
            builders-use-substitutes = true
            download-buffer-size = $((64 * 1024 ** 3)) # 64 GiB
          " \
            $(nix config show --json | jq -r '
              (."system".value, ."max-jobs".value),
              (."system-features".value | join(","))
            ')

      - uses: actions/upload-artifact@main
        with:
          name: home
          path: |
            ~/.ssh
            ~/.config
          include-hidden-files: true
          if-no-files-found: error

      - uses: gacts/run-and-post-run@main
        with:
          run: |
            sudo cp -R ~/.ssh ~/.config /root
            sudo chown -R root:root /root
          post:
            sudo ssh $JUMP_PROXY -NR $ARM_BUILDER:22:localhost:22
