name: Setup ARM remote builder
on:
  workflow_call:
  workflow_dispatch:

jobs:
  setup-arm-builder:
    runs-on: ubuntu-24.04-arm
    steps:
      - run: |
          ssh-keygen -t rsa -N '' -f .ssh/id_rsa
          mv .ssh/id_rsa.pub .ssh/authorized_keys

          printf > .ssh/config "
            BatchMode yes
            StrictHostKeyChecking no
            PasswordAuthentication no

          Host proxy-jump
            HostName ssh-j.com
            User ${{ github.repository }}/${{ github.run_id }}
            RemoteForward arm-builder:22 localhost:22
            ExitOnForwardFailure yes

          Host arm-builder
            ProxyJump proxy-jump
          "

      - uses: actions/checkout@main
      - uses: ./.github/actions/install-detnix
      - run: |
          printf > nix.conf "
            builders = ssh-ng://arm-builder %s - %s - %s
            builders-use-substitutes = true
          " \
            $(nix config show --json | jq -r '
              (."system".value, ."max-jobs".value),
              (."system-features".value | join(","))
            ')

      - uses: actions/upload-artifact@main
        with:
          name: home
          path: .
