name: arm
on:
  push:
  workflow_dispatch:
  schedule:
    - cron: 42 23 * * *

jobs:
  build:
    permissions:
      contents: read

    runs-on: ubuntu-24.04-arm
    steps:
      - uses: DeterminateSystems/nix-installer-action@main
        with:
          extra-conf: |
            lazy-locks = true
            lazy-trees = true
            eval-cores = 0

      - uses: actions/checkout@main
      - uses: cachix/cachix-action@master
        with:
          name: m-bdf
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}

      - run: nix build .#nixOnDroidConfigurations.aarch64-linux.activationPackage
          --accept-flake-config
          --trace-verbose --show-trace
          --print-build-logs --keep-going
          --max-jobs 1
