name: build
on:
  push:
  schedule:
    - cron: 42 23 * * *
  workflow_dispatch:

jobs:
  build:
    permissions:
      contents: read

    runs-on: ubuntu-latest
    steps:
      - uses: cachix/install-nix-action@master
      - uses: cachix/cachix-action@master
        with:
          name: m-bdf
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}

      - uses: actions/checkout@main
      - run: nix flake check
          --accept-flake-config
          --trace-verbose --show-trace
          --print-build-logs --keep-going
          --max-jobs 1

  delete-old-builds:
    needs: build

    permissions:
      actions: write

    runs-on: ubuntu-latest
    steps:
      - uses: Mattraks/delete-workflow-runs@main
        with:
          retain_days: 0
