name: build
on:
  push:
  schedule:
    - cron: 42 23 * * *
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: rm --recursive .git

      - name: Enforce LF line breaks
        run: "! grep --recursive \r"

      - uses: cachix/install-nix-action@v20
        with:
          extra_nix_config: system-features = nixos-test kvm

      - uses: cachix/cachix-action@v12
        with:
          name: m-bdf
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}

      - run: nix flake check --print-build-logs --show-trace

  delete-old-builds:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: Mattraks/delete-workflow-runs@v2
        with:
          retain_days: 0
