name: build
on:
  push:
  schedule:
    - cron: 42 23 * * *

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: rm --recursive .git

      - uses: cachix/install-nix-action@v16
      - uses: cachix/cachix-action@v10
        with:
          name: m-bdf
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}

      - run: nix shell nixpkgs#nixos-install-tools --command
          nixos-generate-config --no-filesystems --dir .
      - run: nix run -- nixpkgs#nixos-rebuild build --flake .#mae
