name: check
on:
  push:
  schedule:
    - cron: 42 23 * * *
  workflow_dispatch:

jobs:
  check:
    permissions:
      contents: read

    runs-on: ubuntu-latest
    steps:
      - uses: cachix/install-nix-action@master
        with:
          install_url: https://install.determinate.systems/nix
          install_options: --no-confirm
          extra_nix_config: extra-platforms = aarch64-linux

      - run: sudo apt update
      - run: sudo apt install qemu-user-static
      - uses: wimpysworld/nothing-but-nix@main

      - uses: cachix/cachix-action@master
        with:
          name: m-bdf
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}

      - uses: actions/checkout@main
      - run: nix flake check
          --accept-flake-config --impure
          --trace-verbose --show-trace
          --print-build-logs --keep-going
          --max-jobs 1

  chore:
    needs: check

    permissions:
      deployments: write
      actions: write

    runs-on: ubuntu-latest
    steps:
      - uses: int128/delete-deployments-action@v1
      - uses: Mattraks/delete-workflow-runs@main
        with:
          retain_days: 0
