name: check
on:
  workflow_run:
    workflows: [droid]
    types: [completed]

jobs:
  check:
    permissions:
      contents: read

    runs-on: ubuntu-latest
    steps:
      - uses: DeterminateSystems/nix-installer-action@main
        with:
          extra-conf: |
            lazy-locks = true
            lazy-trees = true
            eval-cores = 0

      - uses: actions/checkout@main
      # - uses: cachix/cachix-action@master
      #   with:
      #     name: m-bdf
      #     authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}

      - run: nix flake check
          --accept-flake-config
          --trace-verbose --show-trace
          --print-build-logs --keep-going
          --max-jobs 1

  chore:
    needs: check

    permissions:
      deployments: write
      actions: write

    runs-on: ubuntu-latest
    steps:
      - uses: int128/delete-deployments-action@v1
      - uses: Mattraks/delete-workflow-runs@main
        with:
          retain_days: 0
