name: check
on:
  push:
  schedule:
    - cron: 42 23 * * *
  workflow_dispatch:

jobs:
  check:
    permissions:
      contents: read

    runs-on: ubuntu-latest
    steps:
      - run: |
          sudo apt update
          sudo apt remove man-db
          sudo apt install qemu-user-static

      - uses: wimpysworld/nothing-but-nix@main
      - uses: DeterminateSystems/nix-installer-action@main
        with:
          determinate: true
          extra-conf: |
            lazy-locks = true
            lazy-trees = true
            eval-cores = 0
            extra-platforms = aarch64-linux

      - uses: actions/checkout@main
      - uses: cachix/cachix-action@master
        with:
          name: m-bdf
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}

      - run: nix flake check
          --accept-flake-config --impure
          --trace-verbose --show-trace
          --print-build-logs --keep-going
          --download-buffer-size $((2**30)) # 1GiB

  chore:
    needs: check

    permissions:
      deployments: write
      actions: write

    runs-on: ubuntu-latest
    steps:
      - uses: int128/delete-deployments-action@v1
      - uses: Mattraks/delete-workflow-runs@main
        with:
          retain_days: 0
