name: debug
on:
  workflow_dispatch:

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: rm --recursive .git

      - uses: cachix/install-nix-action@v31
      - uses: mxschmitt/action-tmate@v3
