name: debug
on:
  workflow_dispatch:

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt update
      - run: sudo apt install qemu-user-static

      - uses: cachix/install-nix-action@master
        with:
          extra_nix_config: extra-platforms = aarch64-linux

      - uses: actions/checkout@main
      - run: nix flake prefetch-inputs

      - uses: mxschmitt/action-tmate@master
