name: debug
on:
  push:
  workflow_dispatch:

jobs:
  generate-ssh-key:
    runs-on: ubuntu-latest
    steps:
      - run: |
          sudo cp -R /etc/ssh .
          chmod +w ssh
          ssh-keygen -t rsa -N '' -f ssh/id_rsa

      - uses: actions/upload-artifact@main
        with:
          path: ssh


      # - run: |
      #     ssh-keygen -t rsa -N '' -f ~/.ssh/id_rsa
      #     cp ~/.ssh/id_rsa.pub ~/.ssh/authorized_keys

      # - uses: actions/upload-artifact@main
      #   with:
      #     path: ~/.ssh


      # - run: ssh-keygen -t rsa -N '' -f id_rsa

      # - uses: actions/upload-artifact@main
      #   with:
      #     path: id_rsa

    #   - id: export-public-key
    #     run: echo "public-key=$(cat id_rsa.pub)" >> $GITHUB_OUTPUT

    # outputs:
    #   public-key: ${{ steps.export-public-key.outputs.public-key }}

  tmate-aarch64:
    needs: generate-ssh-key

    runs-on: ubuntu-24.04-arm
    steps:
      - uses: actions/download-artifact@main
      - run: |
          mkdir ~/.ssh
          cat ssh/id_rsa.pub ssh/ssh_host_rsa_key.pub
            >> ~/.ssh/authorized_keys
          cat ssh/id_rsa.pub ssh/ssh_host_rsa_key.pub
            >> /etc/ssh/authorized_keys

      # - run: mkdir ~/.ssh && echo > ~/.ssh/authorized_keys
      #     ${{ needs.generate-ssh-key.outputs.public-key }}

      - uses: DeterminateSystems/nix-installer-action@main
        with:
          extra-conf: |
            lazy-locks = true
            lazy-trees = true
            eval-cores = 0
            always-allow-substitutes = true
            builders-use-substitutes = true

      - uses: actions/checkout@main
      - uses: mxschmitt/action-tmate@master

  tmate-x86_64:
    needs: generate-ssh-key

    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@main
      - run: |
          cp -R ssh ~/.ssh
          cp -R ssh /etc/ssh

      - uses: DeterminateSystems/nix-installer-action@main
        with:
          extra-conf: |
            lazy-locks = true
            lazy-trees = true
            eval-cores = 0
            always-allow-substitutes = true
            builders-use-substitutes = true

      - uses: actions/checkout@main
      - uses: mxschmitt/action-tmate@master
