name: Install Determinate Nix
on:
  workflow_call:
  workflow_dispatch:

jobs:
  fetch-nix-install:
    strategy:
      matrix:
        runner:
          - ubuntu-latest
          - ubuntu-24.04-arm

    runs-on: ${{ matrix.runner }}
    steps:
      - uses: DeterminateSystems/nix-installer-action@main
      - run: |
          flake='https://flakehub.com/f/DeterminateSystems/nix-src'
          nix build $flake/*#binaryTarball
          tar -xf result/nix-*.tar.xz

      - uses: actions/upload-artifact@main
        with:
          name: nix-install-${{ runner.arch }}
          path: nix-*
