name: droid
on:
  push:
  workflow_dispatch:
  schedule:
    - cron: 42 23 * * *

env:
  JUMP_PROXY: ${{ github.repository }}@ssh-j.com
  ARM_BUILDER: arm-builder-${{ github.run_id }}

jobs:
  export-home-dir:
    runs-on: ubuntu-24.04
    steps:
      - run: |
          mkdir -p .ssh .config/nix
          ssh-keygen -t rsa -N '' -f .ssh/id_rsa
          cp .ssh/id_rsa.pub .ssh/authorized_keys

          printf > .ssh/config "
            Host * \n StrictHostKeyChecking no
            Host $ARM_BUILDER \n ProxyJump $JUMP_PROXY
          "

          printf > .config/nix/nix.conf "
            builders = ssh-ng://$ARM_BUILDER aarch64-linux - $(nproc)
            builders-use-substitutes = true
            download-buffer-size = $((64 * 1024 ** 3)) # 64 GiB
          "

      - uses: actions/upload-artifact@main
        with:
          name: home
          path: .
          include-hidden-files: true
          if-no-files-found: error

  setup-arm-builder:
    needs: export-home-dir

    runs-on: ubuntu-24.04-arm
    steps:
      - uses: actions/download-artifact@main
      - run: chmod 400 .ssh/id_rsa
      - run: sudo cp -R .* /root
      - run: cp -R .* ~

      - uses: wimpysworld/nothing-but-nix@main
      - uses: DeterminateSystems/nix-installer-action@main

      # - uses: cachix/cachix-action@master
      #   with:
      #     name: m-bdfe; done
      #     authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}

      - run: nix config show

      - run: sudo ssh $JUMP_PROXY -R $ARM_BUILDER:22:localhost:22 -Nf
      - run: |
          sudo execsnoop-bpfcc -l source-stdenv.sh |
          while read _ pid _; do
            echo $pid
            ls -l /proc/$pid/environ
            grep -saPo '(?<=out=)[^\0]+' /proc/$pid/environ
          done

  build-bootstrap-zips:
    needs: export-home-dir

    permissions:
      contents: read

    runs-on: ubuntu-24.04
    steps:
      - uses: actions/download-artifact@main
      - run: chmod 400 .ssh/id_rsa
      - run: sudo cp -R .* /root
      - run: cp -R .* ~

      - uses: wimpysworld/nothing-but-nix@main
      - uses: DeterminateSystems/nix-installer-action@main
        with:
          extra-conf: |
            lazy-locks = true
            lazy-trees = true
            eval-cores = 0

      # - uses: cachix/cachix-action@master
      #   with:
      #     name: m-bdf
      #     authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}

      - run: sleep 10
      - run: nix config show
      - run: sudo ssh $ARM_BUILDER nix config show

      - uses: actions/checkout@main
      - run: nix build .#nixOnDroidBootstrapZips
          --accept-flake-config
          --trace-verbose --show-trace
          --print-build-logs --keep-going

      - if: always()
        run: sudo ssh $ARM_BUILDER pkill execsnoop-bpfcc

      - uses: actions/upload-pages-artifact@main
        with:
          path: result

  deploy-bootstrap-zips:
    needs: build-bootstrap-zips
    concurrency:
      group: ${{ github.workflow }}
      cancel-in-progress: true

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - id: deployment
        uses: actions/deploy-pages@main
