name: droid
on:
  push:
  workflow_dispatch:
  schedule:
    - cron: 42 23 * * *

env:
  JUMP_HOST: ${{ github.repository }}@ssh-j.com
  ARM_BUILDER: ${{ github.run_id }}

jobs:
  generate-ssh-key:
    runs-on: ubuntu-latest
    steps:
      - run: |
          mkdir ssh
          sudo ssh-keygen -t rsa -N '' -f ssh/nixremote
          sudo chmod -R 777 ssh

      - uses: actions/upload-artifact@main
        with:
          path: ssh

  setup-arm-builder:
    needs: generate-ssh-key

    runs-on: ubuntu-24.04-arm
    steps:
      - uses: actions/download-artifact@main
      - run: |
          sudo cp nixremote.pub /root/.ssh/authorized_keys

      - uses: DeterminateSystems/nix-installer-action@main
        with:
          extra-conf: |
            lazy-locks = true
            lazy-trees = true
            eval-cores = 0
            builders-use-substitutes = true
            download-buffer-size = 4398046511104

      - run:
          ssh $JUMP_HOST
            -R $ARM_BUILDER:22:localhost:22
            -o StrictHostKeyChecking=no -Nv

  build:
    needs: generate-ssh-key

    permissions:
      contents: read

    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@main
      - run: |
          echo '
          Host *
            IdentitiesOnly yes
            IdentityFile /root/.ssh/nixremote
            StrictHostKeyChecking no
            # UserKnownHostsFile /dev/null
            PasswordAuthentication no
          ' > config

          sudo cp * /root/.ssh
          sudo chmod 600 /root/.ssh/nixremote
          rm -rf ~/.ssh

      # - run: |
      #     sudo apt update
      #     sudo apt remove man-db
      #     sudo apt install qemu-user-static

      # - uses: wimpysworld/nothing-but-nix@main
      - uses: DeterminateSystems/nix-installer-action@main
        with:
          extra-conf: |
            lazy-locks = true
            lazy-trees = true
            eval-cores = 0
            builders-use-substitutes = true
            download-buffer-size = 4398046511104
            # extra-platforms = aarch64-linux

      - uses: actions/checkout@main
      # - uses: cachix/cachix-action@master
      #   with:
      #     name: m-bdf
      #     authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}

      - run:
          sudo NIX_SSHOPTS="-J $JUMP_HOST"
            $(command -v nix) build .#nixOnDroidConfigurations.aarch64-linux.activationPackage
              --accept-flake-config
              --trace-verbose --show-trace
              --print-build-logs --keep-going
              --builders "$ARM_BUILDER aarch64-linux - - 8"
        # env:
        #   NIX_SSHOPTS: -J $JUMP_HOST

      - uses: actions/upload-pages-artifact@main
        with:
          path: result

  deploy:
    needs: build
    concurrency:
      group: ${{ github.workflow }}
      cancel-in-progress: true

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - id: deployment
        uses: actions/deploy-pages@main
