name: droid
on:
  push:
  workflow_dispatch:
  schedule:
    - cron: 42 23 * * *

jobs:
  setup-arm-builder:
    concurrency:
      group: ${{ github.workflow }}
      cancel-in-progress: true

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-24.04-arm
    steps:
      - id: tmate
        uses: mxschmitt/action-tmate/detached@master

      - run: |
          mkdir tmp
          echo ${{steps.tmate.outputs.ssh-address}} > tmp/index.html

      - uses: actions/upload-pages-artifact@main
        with:
          path: tmp

      - id: deployment
        uses: actions/deploy-pages@main

      - run: sleep infinity

  build:
    permissions:
      contents: read

    runs-on: ubuntu-latest
    steps:
      - uses: DeterminateSystems/nix-installer-action@main
        with:
          extra-conf: |
            lazy-locks = true
            lazy-trees = true
            eval-cores = 0

      - uses: actions/checkout@main
      - uses: cachix/cachix-action@master
        with:
          name: m-bdf
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}

      - run: nix build .#nixOnDroidBootstrapZips
          --accept-flake-config
          --trace-verbose --show-trace
          --print-build-logs --keep-going
          --max-jobs 1
          --builders "ssh://$(
            curl -L https://m-bdf.github.io/nixos
          ) aarch64-linux"

      - uses: actions/upload-pages-artifact@main
        with:
          path: result

  deploy:
    needs: build
    concurrency:
      group: ${{ github.workflow }}
      cancel-in-progress: true

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - id: deployment
        uses: actions/deploy-pages@main
