name: Run nix flake check
on:
  push:
  workflow_dispatch:
  schedule:
    - cron: 42 23 * * *

jobs:
  build-bootstrap-zips:
    permissions:
      contents: read
    uses: ./.github/workflows/droid-bootstrap.yml

  deploy-bootstrap-zips:
    needs: build-bootstrap-zips
    concurrency:
      group: ${{ github.workflow }}
      cancel-in-progress: true

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - id: deployment
        uses: actions/deploy-pages@main

  nix-flake-check:
    needs: build-bootstrap-zips

    permissions:
      contents: read

    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@main
        with:
          name: nix.conf
          path: ~/.config/nix

      # - uses: wimpysworld/nothing-but-nix@main
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: cachix/cachix-action@master
        with:
          name: m-bdf
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}

      - uses: actions/checkout@main
      - run: nix flake check
          --accept-flake-config
          --trace-verbose --show-trace
          --print-build-logs --keep-going
