name: Run nix flake check
on:
  push:
  workflow_dispatch:
  schedule:
    - cron: 42 23 * * *

jobs:
  build-bootstrap-zips:
    permissions:
      pages: write
      id-token: write

    uses: ./.github/workflows/droid-bootstrap.yml
    secrets: inherit

  nix-flake-check:
    needs: build-bootstrap-zips

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: ./.github/actions/install-detnix
        with: ${{ secrets }}

      - run: nix flake check -j1 -L

  respository-chore:
    needs: nix-flake-check

    permissions:
      actions: write
      deployments: write

    runs-on: ubuntu-slim
    steps:
      - uses: int128/delete-deployments-action@v1
      - uses: Mattraks/delete-workflow-runs@main
        with:
          retain_days: 0
