name: Run nix flake check
on:
  push:
  workflow_dispatch:
  schedule:
    - cron: 42 23 * * *

jobs:
  droid-bootstrap:
    permissions:
      contents: read
      pages: write
      id-token: write

    uses: ./.github/workflows/droid-bootstrap.yml

  nix-flake-check:
    needs: droid-bootstrap

    permissions:
      contents: read

    runs-on: ubuntu-latest
    steps:
      - uses: wimpysworld/nothing-but-nix@main
      - uses: DeterminateSystems/nix-installer-action@main

      - uses: actions/download-artifact@main
      - run: |
          chmod 400 .ssh/id_rsa
          cp -R . ~
          sudo cp -R . /root
          sudo chown -R root:root /root

      - uses: cachix/cachix-action@master
        with:
          name: m-bdf
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}

      - uses: actions/checkout@main
      - run: nix flake check
          --accept-flake-config
          --trace-verbose --show-trace
          --print-build-logs --keep-going

  respository-chore:
    needs: nix-flake-check

    permissions:
      actions: write
      deployments: write

    runs-on: ubuntu-latest
    steps:
      - uses: int128/delete-deployments-action@v1
      - uses: Mattraks/delete-workflow-runs@main
        with:
          retain_days: 0
