name: Provide remote access for debugging
on:
  push:
  workflow_dispatch:

jobs:
  setup-arm-builder:
    uses: ./.github/workflows/arm-builder.yml

  start-arm-builder:
    needs: setup-arm-builder

    runs-on: ubuntu-24.04-arm
    steps:
      - uses: actions/download-artifact@main
      - run: |
          chmod 755 ~
          sudo chsh $USER -s /bin/bash
          chmod 400 .ssh/id_rsa
          mv .ssh ~

      # - uses: wimpysworld/nothing-but-nix@main
      - uses: DeterminateSystems/nix-installer-action@main

      - run: ssh proxy-jump -N

  setup-remote-access:
    needs: setup-arm-builder

    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@main
      - run: |
          chmod 755 ~
          mv nix ~/.config
          chmod 400 .ssh/id_rsa
          sudo cp -R .ssh /root
          mv .ssh ~

      # - uses: wimpysworld/nothing-but-nix@main
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: cachix/cachix-action@master
        with:
          name: m-bdf
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}

      - uses: actions/checkout@main
      - uses: owenthereal/action-upterm@main

      - if: always()
        run: ssh arm-builder -f killall ssh
