name: Provide remote access for debugging
on:
  workflow_dispatch:

jobs:
  setup-arm-builder:
    uses: ./.github/workflows/arm-builder.yml

  setup-remote-access:
    runs-on: ubuntu-latest
    steps:
      - uses: wimpysworld/nothing-but-nix@main
      - uses: DeterminateSystems/nix-installer-action@main
        with:
          extra-conf: |
            lazy-locks = true
            lazy-trees = true
            eval-cores = 0

      - run: while ! gn run download; do sleep 5; done

      - run: sudo mkdir /root/.config/nix ~/.config/nix
      - run: sudo cp nix.conf /root/.config/nix
      - run: cp nix.conf ~/.config/nix

      - run: chmod 400 .ssh/id_rsa
      - run: sudo cp -R .ssh /root
      - run: cp -R .ssh ~

      - uses: cachix/cachix-action@master
        with:
          name: m-bdf
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}

      - uses: actions/checkout@main
      - uses: mxschmitt/action-tmate@master
