name: Cleanup repository
on:
  push:
  workflow_dispatch:
  schedule:
    - cron: 42 23 * * *

jobs:
  respository-chore:
    permissions:
      actions: write
      deployments: write

    runs-on: ubuntu-latest
    steps:
      - uses: int128/delete-deployments-action@main
      - uses: Mattraks/delete-workflow-runs@main
        with:
          retain_days: 0
